import type { Metadata } from "next";
import { Fraunces, DM_Sans } from "next/font/google";
import "./globals.css";
import {
  AMFI_ARN,
  EMAIL,
  IS_PRODUCTION_DEPLOYMENT,
  LEGAL_NAME,
  OFFICES,
  OG_DEFAULTS,
  PHONE_TEL,
  REGISTERED_OFFICE,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_TITLE,
  SITE_URL,
  YOUTUBE_CHANNELS,
} from "@/lib/site";

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  axes: ["opsz", "SOFT", "WONK"],
  style: ["normal", "italic"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  /**
   * Without this, any metadata field given a relative URL is a build error —
   * that is the whole reason the site had no Open Graph image slot and no
   * canonical anywhere (audit finding M-03). Declared here in the root layout
   * so every route below inherits it, and every route's relative `/og.png` or
   * `alternates.canonical: "/about"` resolves against the real origin instead
   * of failing. `SITE_URL` is resolved per deployment rather than hardcoded —
   * see the note on it in `lib/site.ts`.
   */
  metadataBase: new URL(SITE_URL),
  title: SITE_TITLE,
  /**
   * The compliance-reviewed wording, and the reasoning behind every clause of
   * it, now lives on `SITE_DESCRIPTION` in `lib/site.ts`. The string is
   * unchanged; it moved so that the search snippet, `og:description` and
   * `twitter:description` all quote the one sentence that was reviewed rather
   * than three separately-drifting copies of it. Read that comment before
   * touching this — the wording is an AMFI constraint, not a style choice.
   */
  description: SITE_DESCRIPTION,

  /**
   * Nested metadata objects merge *shallowly* between segments: a route that
   * exports its own `openGraph` replaces this entire object rather than adding
   * to it. So these defaults reach a child route in exactly one of two ways —
   * the route sets no `openGraph` at all and inherits all of it, or it spreads
   * `OG_DEFAULTS` and re-states `title`, `description` and `url` itself. A
   * route that writes a bare `openGraph: { title }` gets no `og:site_name`,
   * no `og:locale` and no `og:type`.
   *
   * The same rule is why there is no `alternates.canonical` here: inherited
   * shallowly, a root canonical of "/" would have all 19 routes declare the
   * homepage as their canonical URL and ask Google to drop 18 of them.
   */
  openGraph: {
    ...OG_DEFAULTS,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: "/",
  },

  /**
   * No `images` here: X falls back to `og:image`, which `OG_DEFAULTS` now
   * carries — the 1200×630 card generated by `app/opengraph-image.tsx`. A
   * second declaration would only be a second thing to keep in step with it.
   */
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },

  /**
   * Keep every deployment that is not the real site out of the search index.
   *
   * This build currently ships to `platizio-v2.vercel.app` while
   * `www.platizio.com` still serves the legacy site — a complete, publicly
   * crawlable duplicate of all 19 routes. Two identical sites competing is a
   * problem a canonical cannot reliably solve, because a canonical is a hint
   * and Google is free to disagree, especially when it points at a host whose
   * markup does not match.
   *
   * `noindex` is not a hint. It is paired with a crawlable robots.txt on
   * purpose — see the note in `app/robots.ts` — because a directive nobody is
   * allowed to fetch cannot be obeyed. `nocache` and the two snippet limits
   * cover the interim: they stop a preview's copy surviving in a cache or as a
   * rich result after the page itself has dropped out.
   *
   * This flips itself off once the domain is attached or `NEXT_PUBLIC_SITE_URL`
   * is set, because `IS_PRODUCTION_DEPLOYMENT` is derived from the resolved
   * origin rather than from a separate flag someone has to remember.
   */
  robots: IS_PRODUCTION_DEPLOYMENT
    ? { index: true, follow: true }
    : {
        index: false,
        follow: false,
        nocache: true,
        googleBot: { index: false, follow: false, noimageindex: true },
      },
};

/**
 * Organization structured data (audit finding M-04). Without it a search
 * engine has to infer the firm's identity from prose; with it the legal
 * entity, its registration, its offices and its channels are stated once,
 * unambiguously, from the same constants the pages render.
 *
 * Typed as `FinancialService` rather than plain `Organization`: it is a
 * subtype of Organization (via LocalBusiness), so every Organization-level
 * signal — `name`, `url`, `logo`, `sameAs` — still applies, while naming what
 * the entity actually is. `logo` finally gives `public/platizio-logo.png` a
 * consumer; it had been shipping unreferenced (finding L-11).
 *
 * `address` is the registered office named in the Terms, singular, because
 * that is the address *of the entity*; both working offices appear under
 * `location`. A consumer that reads only one address then gets the legal one.
 */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "FinancialService",
  // A stable node id, so a page-level graph can later point at this entity
  // (`publisher`, `provider`) instead of restating it.
  "@id": `${SITE_URL}/#organization`,
  name: SITE_NAME,
  legalName: LEGAL_NAME,
  description: SITE_DESCRIPTION,
  url: SITE_URL,
  logo: `${SITE_URL}/platizio-logo.png`,
  email: EMAIL,
  telephone: PHONE_TEL,
  address: {
    "@type": "PostalAddress",
    ...REGISTERED_OFFICE.postalAddress,
  },
  location: OFFICES.map((office) => ({
    "@type": "Place",
    name: `${office.city} office`,
    address: {
      "@type": "PostalAddress",
      ...office.postalAddress,
    },
  })),
  sameAs: YOUTUBE_CHANNELS.map((channel) => channel.href),
  identifier: {
    "@type": "PropertyValue",
    name: "AMFI Registration Number (ARN)",
    value: AMFI_ARN,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${dmSans.variable} antialiased`}
    >
      <body>
        {/*
          The one `dangerouslySetInnerHTML` in `src/`, and the documented way
          to emit JSON-LD — `next/script` is for executable code, this is data.
          The payload is a real object run through `JSON.stringify`, never an
          interpolated template string, so it cannot be emitted malformed; the
          `<` escape is the sanitising step the Next.js JSON-LD guide asks for,
          preventing any constant that ever grows a `</script>` from closing
          this tag early. It renders nothing, so it is inert with respect to
          the preloader and the entrance choreography below it.
        */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationJsonLd).replace(/</g, "\\u003c"),
          }}
        />
        {children}
      </body>
    </html>
  );
}
