import type { RichBlock } from "@/lib/content-types";

const body: RichBlock[] = [
  { kind: "h2", text: "Introduction and Acceptance" },
  { kind: "p", text: "These master terms and conditions (\"Terms\") govern your access to and use of the online platforms, mobile applications, digital interfaces, distributor portals, service desks, support channels and other services (collectively, the \"Platform\") provided by Platizio Services LLP (\"Platizio\", \"we\", \"us\" or \"our\"). By using the Platform you acknowledge that you have read, understood and agree to be bound by these Terms. If you do not agree to these Terms, you should not access or use the Platform. These Terms apply to all categories of users including investors, prospective investors, leads, distributors, sub-distributors, channel partners and other business partners, but they do not apply to Platizio employees, who are governed by separate internal policies. Certain products or services may be governed by additional product-specific terms, partner agreements, disclosure documents and regulatory documents. In the event of a conflict, the product-specific terms or regulatory documents will prevail for that product or service." },

  { kind: "h2", text: "Legal Entity and Contact Details" },
  { kind: "p", text: "Platizio Services LLP is a limited liability partnership registered in India with LLPIN AAQ-9558, incorporated on 5 December 2019 and having its registered office at Unit No. DGL-229, Second Floor, DLF Galleria Mall, Mayur Vihar-1, Delhi, India – 110092. Platizio acts as a technology-enabled platform and distributor of a wide range of financial products. Platizio is an AMFI-registered mutual fund distributor (ARN 341407). It is not registered as a securities broker, investment adviser, portfolio manager or research analyst. To contact us please write to support@platizio.com for general queries or grievances@platizio.com for complaints. Our business hours are Monday to Friday, 9:00 AM to 5:00 PM Indian Standard Time." },

  { kind: "h2", text: "Definitions" },
  { kind: "p", text: "For the purpose of these Terms: \"Investor\" means any individual or entity using the Platform to evaluate, subscribe to or transact in financial products. \"Sub-distributor\" means any mutual fund distributor, registered investment intermediary or other business partner authorised by Platizio to access the Platform and service its clients. \"Product Provider\" means a mutual fund, trust, alternative investment fund, portfolio manager, issuer, bank, non-banking financial company, insurance company or other regulated entity whose products are available on the Platform. \"Third-party Service Provider\" includes any entity providing KYC, identity verification, payment, remittance, custodial, technology, compliance, audit or other services to Platizio or Product Providers." },

  { kind: "h2", text: "Nature of the Platform" },
  { kind: "p", text: "Platizio operates a technology platform that enables investors to discover, learn about, and transact in various financial products through authorised sub-distributors and product providers. Platizio facilitates onboarding, compliance checks, transaction processing, reporting, and communications, but does not manufacture financial products. Platizio does not hold investor funds or securities, does not provide personalised investment advice, research or portfolio management, and does not act as custodian, broker, underwriter or issuer for any product. Any information provided on the Platform is for general informational and educational purposes only." },

  { kind: "h2", text: "Product Universe and Supplemental Terms" },
  { kind: "p", text: "The Platform may provide access to a range of financial products, including without limitation mutual funds, Systematic Investment Fund (SIFs), portfolio management services (PMS), alternative investment funds (AIFs), bonds, fixed deposits, loan against securities (LAS), structured products, unlisted shares, international investments products, insurance products, pension products and other approved financial instruments (collectively, \"Products\"). Not all Products may be available at all times or to all users. Each Product is subject to its own offer document, private placement memorandum, information memorandum, key information document, scheme information document, terms of service, prospectus or other regulatory document provided by the Product Provider. In addition, Platizio may issue supplemental terms for specific products or services. To the extent of any inconsistency between these Terms and such product-specific terms or regulatory documents, the latter will prevail." },

  { kind: "h2", text: "No Investment Advice" },
  { kind: "p", text: "Platizio is a distribution and facilitation platform. Nothing on the Platform shall be construed as investment, tax, legal or accounting advice, recommendation or opinion. Platizio does not consider your financial circumstances, risk appetite or investment objectives. You are solely responsible for determining whether any Product is appropriate for your particular circumstances and for seeking independent professional advice where necessary. Sub-distributors and third-party advisers accessing the Platform are responsible for complying with all regulatory requirements when providing advice or recommendations to their clients. No information, whether oral or written, obtained through the Platform shall create any warranty or representation by Platizio." },

  { kind: "h2", text: "Eligibility" },
  { kind: "p", text: "You represent that you are of legal age to enter into binding agreements under Indian law and have the legal authority to access the Platform. Individuals who are minors, legally incapacitated or otherwise restricted from investing may not use the Platform. For certain Products, you must be an Indian resident or otherwise eligible under Indian law; non-resident Indians or foreign investors may be subject to additional conditions. Platizio reserves the right to deny or terminate access to the Platform at its discretion, including for failure to complete KYC/AML requirements, inaccurate information, regulatory restrictions, sanctions, suspected fraud, non-payment of charges or breach of these Terms." },

  { kind: "h2", text: "Account Registration, KYC and Security" },
  { kind: "p", text: "To access certain features you may be required to register an account, complete know-your-customer (KYC) formalities and provide supporting documents such as PAN, Aadhaar, passport, address proof, bank proof, photograph and signature, as well as declarations such as FATCA/CRS, Politically Exposed Person, risk profile, source of funds and LRS where applicable. KYC and anti-money laundering (AML) compliance are carried out by regulated KYC registrars, product providers, banks and other third-party service providers. You agree that Platizio may share your personal data with such entities to facilitate KYC/AML, and that your onboarding may be rejected or delayed if your information is incomplete or inconsistent. You are responsible for maintaining the confidentiality of your login credentials and restricting access to your devices. Any instructions received through your credentials will be deemed to have been given by you." },

  { kind: "h2", text: "Sub-distributor and Partner Access" },
  { kind: "p", text: "Sub-distributors authorised by Platizio may use the Platform to onboard investors, initiate transactions, view and manage client portfolios, download reports, track commissions and communicate with clients. Sub-distributors must hold valid regulatory registrations (such as ARN, EUIN or other licences and valid NISM certificates), complete know your distributor (KYD) checks, adhere to the mutual fund code of conduct and other applicable laws, and execute a separate sub-distributor agreement with Platizio. Sub-distributors must not mis-sell, provide unauthorised investment advice, promise returns or engage in any fraudulent, negligent or illegal activity. Platizio may monitor the activities of sub-distributors and terminate access for non-compliance. Distributors are solely responsible for the content of their communications with investors." },

  { kind: "h2", text: "Transactions and Third-Party Execution" },
  { kind: "p", text: "All transactions in Products are executed by or through the relevant Product Provider or an authorised third-party service provider. Platizio does not accept or hold investor funds or securities. Orders placed on the Platform are transmitted to the Product Provider, its registrar and transfer agent, custodian, bank or authorised exchange platform for execution and settlement. Execution is subject to acceptance by the Product Provider and applicable regulatory, legal and procedural requirements. Transactions may be rejected, delayed or cancelled due to reasons including cut-off times, incomplete documentation, insufficient funds, regulatory restrictions, market conditions, system downtime or failure by third-party service providers. Platizio is not responsible for execution delays or errors caused by third parties." },

  { kind: "h2", text: "Fees, Charges and Commission Disclosure" },
  { kind: "p", text: "Use of the Platform may be subject to transaction charges, platform fees, convenience fees, bank remittance charges, custodian fees, registrar fees, regulatory fees, taxes and other charges levied by Product Providers or third-party service providers. Platizio may receive distribution commissions, trail fees, referral fees or revenue share from Product Providers or other partners in relation to the Products. Such remuneration may vary by product, provider and commercial arrangement. Platizio may share a portion of this remuneration with sub-distributors in accordance with separate agreements. Any fees charged directly to investors will be disclosed during the relevant transaction or on the fee schedule published on the Platform. Fees once paid may be non-refundable unless otherwise specified." },

  { kind: "h2", text: "Investment Risks and Disclaimers" },
  { kind: "p", text: "Investments in financial products are subject to market risk, credit risk, interest rate risk, liquidity risk, reinvestment risk, counterparty risk, currency risk, regulatory risk, operational risk, technology risk and other risks. Past performance is not indicative of future returns. Mutual funds are subject to market and other risks; read all scheme related documents carefully. PMS and AIF products are meant for sophisticated investors and may be illiquid; minimum investment thresholds and lock-in may apply. Bonds and fixed income instruments are exposed to default and interest rate risk. LAS involves borrowing risk and collateral liquidation. Structured products and unlisted shares carry high risk and may not be easily transferable. International investments involve currency risk, foreign market risk, political risk and differential tax treatment. Investors should read all product-specific risk disclosures, offer documents and consult their independent advisers before investing. Platizio does not guarantee any returns or principal protection." },

  { kind: "h2", text: "Communications and Electronic Consent" },
  { kind: "p", text: "By using the Platform you consent to receive communications from Platizio, Product Providers and sub-distributors through email, SMS, telephone calls, WhatsApp, in-app notifications, push notifications, web notifications and other electronic means. Communications may include transactional alerts, account statements, updates, confirmations, reminders, disclosures, marketing messages and surveys. Telephone calls and interactions may be recorded for quality, training, compliance and dispute resolution purposes. You may opt-out of marketing communications but will continue to receive essential transactional and legal notifications. You agree to accept electronic records and signatures as valid and binding in accordance with applicable law." },

  { kind: "h2", text: "Privacy and Data Protection" },
  { kind: "p", text: "Our practices with respect to personal data are described in the Platizio Privacy Policy, which is incorporated by reference into these Terms. The Privacy Policy explains what personal data we collect, how we use it, the legal basis of processing, with whom we share it, and your rights under the Digital Personal Data Protection Act, 2023 of India. By using the Platform you acknowledge that you have read the Privacy Policy and consent to the collection, use and disclosure of personal data as described therein." },

  { kind: "h2", text: "Platform Availability and Third-Party Services" },
  { kind: "p", text: "The Platform is provided on an \"as is\" and \"as available\" basis. While Platizio endeavours to maintain a secure and reliable Platform, we do not warrant that the Platform will be uninterrupted, error-free or free of viruses. Access may be limited or unavailable during scheduled maintenance or due to factors beyond our control. The Platform may contain links to third-party websites or integrate third-party services. Platizio does not control and is not responsible for the content or practices of such third parties. Your use of third-party services is subject to their terms and policies." },

  { kind: "h2", text: "Intellectual Property" },
  { kind: "p", text: "All rights, title and interest in the Platform, including its software, content, design, logos, trademarks, service marks, domain names and other intellectual property, are owned by Platizio or its licensors. You are granted a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform for personal or internal business purposes in accordance with these Terms. You shall not copy, modify, distribute, sell, rent, reverse engineer or create derivative works of the Platform. Third-party marks and logos remain the property of their respective owners." },

  { kind: "h2", text: "Suspension and Termination" },
  { kind: "p", text: "Platizio may suspend or terminate your access to the Platform and any agreements with you with immediate effect if you breach these Terms, provide false or misleading information, engage in unauthorised advice or mis-selling, violate applicable laws, fail to pay fees, misuse or attempt to compromise the Platform, or if required by a Product Provider, regulator or court order. Upon termination, any ongoing transactions may be completed or cancelled at the discretion of the Product Provider. Termination does not affect obligations that by their nature should survive, including confidentiality, indemnity, limitation of liability and governing law provisions." },

  { kind: "h2", text: "Indemnity" },
  { kind: "p", text: "You agree to indemnify and hold harmless Platizio, its partners, directors, officers, employees, representatives and agents from and against any losses, liabilities, claims, damages, costs and expenses (including reasonable legal fees) arising out of or relating to (i) your breach of these Terms, (ii) your violation of any law or rights of a third party, (iii) your negligence, fraud or misconduct, (iv) your use of the Platform or (v) any mis-selling, unauthorised advice or misrepresentation by a sub-distributor or other partner acting on your behalf." },

  { kind: "h2", text: "Limitation of Liability" },
  { kind: "p", text: "To the maximum extent permitted by law, Platizio shall not be liable for any indirect, consequential, incidental, special, punitive or exemplary damages, or for any loss of profits, revenue, business or data, arising out of or in connection with the Platform, even if we have been advised of the possibility of such damages. Platizio's total cumulative liability arising out of or relating to the Platform shall not exceed the amount of fees paid by you to Platizio for the specific service giving rise to the claim during the twelve (12) months preceding the event." },

  { kind: "h2", text: "Force Majeure" },
  { kind: "p", text: "Platizio shall not be liable for any failure or delay in performing any obligation under these Terms if such failure or delay is due to events beyond its reasonable control, including acts of God, natural disasters, epidemic or pandemic, war, terrorism, civil unrest, governmental action, labour strike, network failure or shortage of power, utilities or materials." },

  { kind: "h2", text: "Governing Law and Dispute Resolution" },
  { kind: "p", text: "These Terms shall be governed by and construed in accordance with the laws of India. The courts of Delhi shall have exclusive jurisdiction over any disputes arising under or relating to these Terms, subject to the arbitration clause below. Any dispute, controversy or claim arising out of or relating to these Terms that cannot be amicably resolved within thirty (30) days shall be referred to and finally resolved by arbitration under the Arbitration and Conciliation Act, 1996 by a sole arbitrator mutually agreed by both parties. The seat and venue of arbitration shall be Delhi, India. The language of arbitration shall be English. The award shall be final and binding on the parties and may be enforced in any court of competent jurisdiction." },

  { kind: "h2", text: "Miscellaneous" },
  { kind: "p", text: "These Terms constitute the entire agreement between you and Platizio with respect to the subject matter herein and supersede all prior or contemporaneous understandings. If any provision is held to be invalid or unenforceable, the remaining provisions shall continue in full force. Platizio may assign or transfer its rights and obligations under these Terms to any person without your consent. You may not assign your rights under these Terms without Platizio's prior written consent. No delay or failure by Platizio to exercise any right shall be deemed a waiver. The headings are for convenience only and shall not affect interpretation. Any notices under these Terms shall be given via email to the addresses specified herein." },

  { kind: "h2", text: "Contact and Grievance Redressal" },
  { kind: "p", text: "If you have any questions or grievances regarding the Platform or these Terms, please contact our Grievance Officer: Anuj Pal, Operations and Compliance Officer, at grievances@platizio.com or write to our registered office at Unit No. DGL-229, Second Floor, DLF Galleria Mall, Mayur Vihar-1, Delhi, India – 110092. We will acknowledge complaints within 24 hours and aim to resolve them within 15 business days. For general support, please write to support@platizio.com." },
];

export default body;
